### ISSUE TITLE
Update ไม่สําเร็จมีการ ERROR

### ISSUE THREAD

**Issue by Apiphoom** [MakerAsia/KBProIDE#18]
![IMG_0023](https://user-images.githubusercontent.com/48949523/61588713-6ce1ed80-abca-11e9-841c-0f52655b430f.jpg)
![unnamed (4)](https://user-images.githubusercontent.com/48949523/61588715-6eabb100-abca-11e9-9929-9707470d6202.jpg)

**Comment by comdet** [comment]
แก้ไขใน version ใหม่แล้วนะครับ
