### ISSUE TITLE
เพิ่มบอร์ดและปลั๊กอิน จากลิ้ง GitHub ที่ชื่อมี underscore (_) ไม่ได้

### ISSUE THREAD

**Issue by maxpromer** [MakerAsia/KBProIDE#2]
คาดว่าเกิดจาก

https://github.com/MakerAsia/KBProIDE/blob/2e38cad3a33251f6f248bd2360f8e1422ad79bb7/src/engine/components/plugin/Toolbar.vue#L396

และ

https://github.com/MakerAsia/KBProIDE/blob/2e38cad3a33251f6f248bd2360f8e1422ad79bb7/src/engine/components/board_selector/ToolbarBoard.vue#L459

ไม่ได้ใส่ underscore (_) ไว้

**Comment by NAzT** [comment]
https://github.com/MakerAsia/KBProIDE/commit/40f426eed0c42d68fe981a16b43ada833be05182
