### ISSUE TITLE
setup เสร็จแล้วรันไม่ได้ครับ ลองทั้ง32/64 บน วินโดวส์ 10 

### ISSUE THREAD

**Issue by kruboon** [MakerAsia/KBProIDE#23]
Unhandled Error
Error: EPERM: operation not permitted, open 'C:/Program Files (x86)/kbide/INSTALLED'
    at Module.56d7 (app://./js/app.c9a3c60d.js:1:106392)
    at s (app://./js/app.c9a3c60d.js:1:5376)
    at Object.0 (app://./js/app.c9a3c60d.js:1:13875)
    at s (app://./js/app.c9a3c60d.js:1:5376)
    at a (app://./js/app.c9a3c60d.js:1:388)
    at 0 (app://./js/app.c9a3c60d.js:1:13840)
    at app://./js/app.c9a3c60d.js:1:13845

**Comment by comdet** [comment]
เนื่องจากโปรแกรมต้องการเขียนไฟล์ INSTALLED แต่ติด permission ไม่สามารถเขียน folder ได้
รบกวนติดตั้งแบบโดยเลือกเป็น user ธรรมดา หรือเลือกใช้แบบ portable ครับ
![windows install](https://raw.githubusercontent.com/MakerAsia/KBProIDE/master/docs/images/install_warning.jpg)

**Comment by kruboon** [comment]
ขอบคุณครับ  ลองใช้ portable แล้ว ok ครับ
ขอถามครับ บนบอร์ดคิดไบรท์ รับอินพุทอนาล็อกได้ไหมครับ ถ้าไม่ใช้บอร์ดเสริม
ต้องการใช้บอร์ดวัดค่า ความต่างศักย์ เพื่อเปรียบเทียบ
ตรวจจับการเปลี่ยนแปลงแสงตามทิศทางแหล่งกำเนิดแสง ครับ ขอคำชี้แนะด้วยครับ

ในวันที่ ส. 3 ส.ค. 2019 เวลา 14:06 comdet <notifications@github.com>
เขียนว่า:

**Comment by paul0003** [comment]
กรุณาโพสต์คำถามเกี่ยวกับ kid bright ในหน้าเพจ  kid bright ครับ
