### ISSUE TITLE
ไม่สามารถใช้ Built-In Library ของ Board Arduino ได้

### ISSUE THREAD

**Issue by teedev** [MakerAsia/KBProIDE#29]
ตอนนี้ผมไม่สามารถเรียกใช้ I2C ที่อยู่ใน KBIDE/platforms/arduino-avr/sdk/libraries/ กับบอร์ด Arduino ได้ครับ

ขอบคุณครับ

**Comment by comdet** [comment]
fixed in this commit: https://github.com/MakerAsia/kbide-arduino-avr-platform/commit/177896f9de582d6979b90824f11c19260bdc033b
แก้ไขให้ใน repo แล้วนะครับ แต่ตัว patch update น่าจะออกเร็ว ๆ นี้ครับ
