### ISSUE TITLE
KBIDE Linux setup install.sh error ครับ

### ISSUE THREAD

**Issue by nogamenolifeth** [MakerAsia/KBProIDE#30]
รายละเอียดตามนี้ครับ

> sudo ./install.sh
> Adding desktop shortcut, menu item and file associations for KB-IDE...xdg-mime: file '/home/yuki/Downloads/KBIDE/resources/makerasia-kbide.xml' does not exist
> 
> 
> rm: cannot remove '/usr/local/bin/kbide': No such file or directory
> Removing symlink failed. Hope that's OK. If not then rerun as root with sudo.
> sed: can't read /home/yuki/Downloads/KBIDE/resources/desktop.template: No such file or directory
> xdg-icon-resource: file '/home/yuki/Downloads/KBIDE/resources/icons/icons.png' does not exist
> xdg-mime: file '/home/yuki/Downloads/KBIDE/resources/makerasia-kbide.xml' does not exist
> 
>  done!
>

**Comment by comdet** [comment]
ใน version ใหม่จะไม่มีไฟล์ install.sh แล้วนะครับ สามารถแตก zip ออกมาแล้วรัน kbide ในนั้นได้เลย

**Comment by nogamenolifeth** [comment]
หากต้องการลงไปในเครื่องแบบมี icon ให้เรียกใช้ต้องทำอย่างไรครับ
