### ISSUE TITLE
ตัวแปร = ตัวแปร จะขึ้น #VARIABLEundefined

### ISSUE THREAD

**Issue by fxprime** [MakerAsia/KBProIDE#31]
สวัสดีครับ ขอบคุณทีมพัฒนามากๆสำหรับเครื่องมือดี ๆ keep up good work ครับ 

วันนี้เจอปัญหาเวลาให้ค่าตัวแปร = ตัวแปรอีกตัวที่เป็นชนิด int 
ตัวแปรที่โดนใส่ค่าจะกลายเป็นประเภท undifine ทันที แต่พอใส่ค่าเป็น math ก็จะกลับมาเป็น int ปกติ  คิดว่าคงไปอ้างอิงประเภทตัวแปรจากตัวแปรอีกตัวยังไม่ได้ใช่รึป่าวครับ  

ถ้าเราให้การกำหนด type ตัวแปร ถูกกำหนดครั้งเดียวตอนให้ค่าเริ่มต้นจะดีไหมครับ

![af](https://user-images.githubusercontent.com/28912511/65832223-0d4f3f00-e2eb-11e9-9c9f-87f9cd5f816d.JPG)

**Comment by comdet** [comment]
fixed : https://github.com/MakerAsia/KBProIDE/commit/801707a60fa16db8e6c5f03a25490387fcd6f5fe
แก้ไขให้แล้ว แต่อาจจะรออัพเดทพร้อมกับ version ใหม่นะครับ
ชนิดของตัวแปรจะโยงกันไปตลอดที่มีการ set ค่า เช่น
ตัวแปร test เอา Boolean มาต่อ บล็อคของตัวแปร test จะเป็นชนิด Boolean อัตโนมัติ (ถ้าไม่ได้กำหนดจะเป็น int) ถ้าเอา test2 มาต่อกับ test ตัวแปร test2 จะเป็น Boolean ด้วย และเอาไปต่อกับ if (ที่รับ Boolean ได้)
แต่ถ้าแก้ test เป็น String ตัวแปรที่โยงกันจะเป็น String อัตโนมัติ และ test2 จะหลุดออกจาก if ทันที (ต่างชนิดกัน)
![image](https://user-images.githubusercontent.com/4876771/65849603-72e80d80-e375-11e9-8eb9-e3cbb59aee54.png)
