### ISSUE TITLE
Fatal Error หลังจากลบตัวอักษรตอนใส่ input parameter บนฟังก์ชัน

### ISSUE THREAD

**Issue by fxprime** [MakerAsia/KBProIDE#32]
สวัสดีครับ 

   เวลาเราใส่ Function parameter ถ้าลบตัวอักษรจนหมดและกด backspace อีกครั้งจะเกิด error ที่ทำให้ระบบทำงานต่อไม่ได้ มีวิดีโอประกอบการทำ error ซ้ำครับ

https://youtu.be/kXu5RFMAwLw

**Comment by comdet** [comment]
fixed https://github.com/comdet/vue-blockly/commit/f036a887ddc2732e68bc65fedd811f9c94eb7e64
and https://github.com/MakerAsia/KBProIDE/commit/a9142518ed2cb30723939c2c19da90561b8cf30e
