### ISSUE TITLE
win10 win7 คอมไพล์ปรกติผ่าน แต่ compile and run ติด Error

### ISSUE THREAD

**Issue by Lieonkp** [MakerAsia/KBProIDE#6]
Error: Command failed: "C:\Program Files\kbide\platforms\esp-idf\.\tools\xtensa-esp32-elf\bin\xtensa-esp32-elf-ar" cru "C:\Program Files\kbide\boards\esp32-doit\build\30-ae-a4-04-28-30\libmain.a" C:\Program Files\kbide\boards\esp32-doit\build\30-ae-a4-04-28-30\KBProTime.o C:\Program Files\kbide\boards\esp32-doit\build\30-ae-a4-04-28-30\KBProTime.o C:\Program Files\kbide\boards\esp32-doit\build\30-ae-a4-04-28-30\user_app.o C:\Program Files\kbide\boards\esp32-doit\build\30-ae-a4-04-28-30\main.o C:\Program Files\kbide\platforms\esp-idf\.\tools\xtensa-esp32-elf\bin\xtensa-esp32-elf-ar: C:\Program: No such file or directory
![KbErr](https://user-images.githubusercontent.com/41953148/59803298-46077180-9315-11e9-8f4f-d25a34f30a4f.jpg)

**Comment by comdet** [comment]
ถ้าโปรแกรมถูกติดตั้งหรือรันเป็นแบบ Admin จะรัน tool ไม่ได้ครับ ตอนติดตั้งให้เลือกเป็นแบบ only for me จะแก้ปัญหานี้ได้

![image](https://user-images.githubusercontent.com/4876771/59817050-921fd980-9348-11e9-8673-0c9fb7baacdd.png)

**Comment by Lieonkp** [comment]
ขอบคุณครับ

ในวันที่ พฤ. 20 มิ.ย. 2019 10:46 comdet <notifications@github.com> เขียนว่า:
